# Generated by Django 3.0.6 on 2020-07-28 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupbagitem',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Notify When Expired'),
        ),
        migrations.AlterField(
            model_name='makeupbagitem',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='makeupbagitem',
            name='open_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='makeupproduct',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='makeupproduct',
            name='expiry',
            field=models.IntegerField(default=0),
        ),
    ]
