# Generated by Django 3.0.6 on 2020-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0004_auto_20200728_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeupproduct',
            name='category',
            field=models.CharField(choices=[('powder', 'Powder'), ('cream', 'Cream'), ('pencil', 'Pencil'), ('liquid', 'Liquid'), ('gel', 'Gel'), ('palette', 'Palette'), ('contour', 'Contour'), ('bb_cc', 'BB/CC'), ('concealer', 'Concealer'), ('mineral', 'Mineral'), ('highlighter', 'Highlighter'), ('lipstick', 'Lipstick'), ('lip_gloss', 'Lip Gloss'), ('lip_stain', 'Lip Stain'), ('none', 'N/A')], max_length=16),
        ),
    ]
