# Generated by Django 3.0.6 on 2020-07-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0005_auto_20200728_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('alcohol free', 'Alcohol-Free'), ('Canadian', 'Canadian'), ('CertClean', 'CertClean'), ('Chemical Free', 'Chemical-Free'), ('cruelty free', 'Cruelty-Free'), ('Dairy Free', 'Dairy-Free'), ('EWG Verified', 'EWG Verified'), ('EcoCert', 'EcoCert'), ('Fair Trade', 'Fair Trade'), ('Gluten Free', 'Gluten-Free'), ('Hypoallergenic', 'Hypoallergenic'), ('Natural', 'Natural'), ('No Talc', 'No Talc'), ('Non-GMO', 'Non-GMO'), ('oil free', 'Oil-Free'), ('Organic', 'Organic'), ('Peanut Free', 'Peanut-Free'), ('purpicks', 'Purpicks'), ('silicone free', 'Silicone-Free'), ('Sugar Free', 'Sugar-Free'), ('USDA Organic', 'USDA Organic'), ('Vegan', 'Vegan'), ('water free', 'Water-Free'), ('CUSTOM', 'User-Made')], max_length=32),
        ),
    ]
