# Generated by Django 3.0.6 on 2020-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0008_auto_20200803_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
