# Generated by Django 3.0.6 on 2020-08-11 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0009_collection_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='banner_num',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
