# Generated by Django 3.0.6 on 2020-08-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0010_auto_20200811_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
