# Generated by Django 3.0.6 on 2020-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0012_auto_20200816_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupbagitem',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
