# Generated by Django 3.0.6 on 2020-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0013_makeupbagitem_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='has_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
